server:
  port: ${ITM_PLATFORM_AUDIT_SERVICE_PORT:9292}

spring:
  application:
    name: audit-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:${ITM_PLATFORM_DATABASE_URL:postgresql://localhost:5432/postgres}?currentSchema=audit_service
    username: ${ITM_PLATFORM_DATABASE_USERNAME:postgres}
    password: ${ITM_PLATFORM_DATABASE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    open-in-view: false


  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ITM_PLATFORM_KEYCLOAK_ISSUER_URI:https://keycloak.migration.it-mentor.space/realms/ITM-Platform}

  kafka:
    bootstrap-servers: ${ITM_PLATFORM_KAFKA_HOST:localhost:9092}
    consumer:
      group-id: audit-group
      auto-offset-reset: earliest
      auto-commit-interval: 100ms
      session-timeout: 15000ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
    topic:
      # Сюда записываем топики